[build]
  command = "npm install && npm run build"
  publish = "out"
[build.environment]
  NODE_VERSION = "20.18.0"
  NEXT_PRIVATE_TARGET = "static"
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
